tabWidth: 4
printWidth: 100
endOfLine: crlf
trailingComma: none
bracketSameLine: true
quoteProps: consistent

overrides:
  - files: ["*.json", "*.yaml"]
    options:
      tabWidth: 2
  - files: ["*.css", "*.jsx"]
    options:
      singleQuote: true
      printWidth: 20000
